In [ ]:
# ->for working n-dimensional arrays
# ->number of dimensions of the array is called rank of the array
# ->An array class in Numpy is called as ndarray
# ->They offer automatic vectorization and broadcasting.
# ->They provide efficient memory management, ufuncs(universal functions), support various data types, and are flexible with Indexing and slicing. 
# ->Since, sliced array holds a range of elements of the original array, modifying content with the help of sliced array modifies the original array content.
# Methods in Numpy:

#     https://www.geeksforgeeks.org/python-numpy/#:~:text=dtype%20in%20NumPy-,Methods%20in%20Numpy%3A,-all()

# Why is the Numpy Array so Fast?
#     ->Homogeneous Data
#     ->Fixed Data type
#     ->contiguous memory
# Data Allocation in Numpy Array:
#     ->data is allocated contiguously in memory,
#     ->well-defined layout consisting of:
#         ->data buffer:
#             ->single, flat block of memory that stores the actual elements of the array, regardless of its dimensionality
#         ->shape:
#             ->tuple of integers that represents the dimensions along each axis
#         ->Strides: 
#             ->Strides are tuples of integers that define the number of bytes to step in each dimension when moving from one element to the next.
        
# Vectorization in Python:
#     ->code is computationally efficient, we will use vectorization.
#     ->Vectorization is used to speed up the Python code without using loop. Using such a function can help in minimizing the running time of code efficiently


# What is NumPy Array Broadcasting:
#     ->Broadcasting provides a means of vectorizing array operations, therefore eliminating the need for Python loops. This is because NumPy is implemented in C Programming, which is a very efficient language.

# Syntax: numpy.fromiter(iterable, dtype, count=-1)
# Syntax:  numpy.arange( start , stop, step , dtype=None )
# Syntax: numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)


# ->The list can be homogeneous or heterogeneous.
# ->Elements of a list need not be contiguous in memory.

# Comparison between Numpy array and Python List:
#     Python Lists:
#         ->Element Overhead(additional info)
#         ->Datatype(memory efficiency)
#         ->Memory Fragmentation(not contiguous)
#         ->Performance
#         ->Functionality
#     NumPy Arrays:
#         ->Numpy Arrays
#             ->Homogeneous Data
#             ->Fixed Data Type
#             ->Contiguous Memory
#             ->Array Metadata
#             ->Performance

# Advantages of using Numpy Arrays Over Python Lists:
#     ->Consumes less memory.
#     ->Fast as compared to the python List.
#     ->Convenient to use.

# ->print("No. of dimensions: ", arr.ndim)


In [156]:

import array
import numpy as np
from matplotlib import pyplot as plt

In [ ]:
arr = np.array([[[1, 2], [3, 4]],
                [[5, 6], [7, 8]]])

arr1=arr.sum(axis=0)
arr2=arr.sum(axis=1)
arr3=arr.sum(axis=2)
print(arr1)
print(arr2)
print(arr3)

# Index_arr = arr[[1, 1, 0, 3], 
#                 [3, 2, 1, 0]]
# print ("\nElements at indices (1, 3), "
#     "(1, 2), (0, 1), (3, 0):\n", Index_arr)

# arr=np.array(["a","b","raghav"])
# print(arr[:2])
# ['a' 'b']

In [ ]:
# array[start:stop:step]
# array[row_slice, column_slice]

In [ ]:
# Create a sequence of integers from 10 to 1 with a step of -2
a = np.arange(10, 1, -2) 
print("\n A sequential array with a negative step: \n",a)
# Indexes are specified inside the np.array method.
newarr = a[[0,1,2]]
# newarr = a[np.array([3, 1, 2 ])]
print("\n Elements at these indices are:\n",newarr)


In [ ]:
a = np.arange(20) 
print("\n Array is:\n ",a) 
print("\n a[15]=",a[15])
# a[start:stop:step]
print("\n a[-8:17:1] = ",a[-8:17:1]) 
print("\n a[10:] = ",a[10:])

b = np.array([[[1, 2, 3],[4, 5, 6]], 
                [[7, 8, 9],[10, 11, 12]]]) 
print(b[...,1]) #Equivalent to b[: ,: ,1 ]
print(b[: ,: ,: ])


In [ ]:
# You may wish to select those elements whose
# sum of row is a multiple of 10.

b = np.array([[5, 5],[4, 5],[16, 4]])
sumrow = b.sum(1)
# print(sumrow)
print(b[sumrow%10==0])

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])

c=np.dot(a,b)
d=np.outer(a,b)
e=np.multiply(a,b)
print(c)
print(d)
print(e)

# array are compatible because of same Dimension 
# c = a * b

In [ ]:
macros = np.array([ 
  [0.8, 2.9, 3.9], 
  [52.4, 23.6, 36.5], 
  [55.2, 31.7, 23.9], 
  [14.4, 11, 4.9] 
   ]) 
  
result = np.zeros_like(macros) 
  
cal_per_macro = np.array([3, 3, 8]) 
  
for i in range(macros.shape[0]): 
    result[i, :] = macros[i, :] * cal_per_macro 

result

In [ ]:
v = np.array([1, 2, 3])   
w = np.array([4, 5])     
  
# Outer product of vectors v and w 
print(np.reshape(v, (3, 1)) * w)

In [ ]:
import numpy as np 
import matplotlib.pyplot as plt 
  
# Computes x and y coordinates for  
# points on sine and cosine curves 
x = np.arange(0, 3 * np.pi, 0.1) 
y_sin = np.sin(x) 
y_cos = np.cos(x) 
  
# Plot the points using matplotlib 
plt.plot(x, y_sin) 
plt.plot(x, y_cos) 
plt.xlabel('x axis label') 
plt.ylabel('y axis label') 
plt.title('Sine and Cosine') 
plt.legend(['Sine', 'Cosine']) 
  
plt.show()

In [ ]:
iterable = (a*a for a in range(8))
type(iterable)
arr = np.fromiter(iterable, float)
print(arr)

In [ ]:
np.linspace(3.5, 10, 5,endpoint=False,retstep=True,axis=0)

In [ ]:
# Syntax: numpy.empty(shape, dtype=float, order=’C’)
np.empty([4, 3],dtype = np.float64)

In [ ]:
# Syntax: numpy.ones(shape, dtype=None, order=’C’)
# Syntax: numpy.zeros(shape, dtype=None)

In [ ]:
Var = [[[1]], ["for"], "Geeks",3.0]
print(Var)

In [ ]:
# Python program to demonstrate
# basic array characteristics
import numpy as np

# Creating array object
arr = np.array([[1, 2, 3],
                [4, 2, 5]])

# Printing type of arr object
print("Array is of type: ", type(arr))

# Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)

# Printing shape of array
print("Shape of array: ", arr.shape)

# Printing size (total number of elements) of array
print("Size of array: ", arr.size)

# Printing type of elements in array
print("Array stores elements of type: ", arr.dtype)

In [ ]:
# Create a constant value array of complex type
d = np.full((3, 3), 6, dtype='complex')
print(d)

In [ ]:
# Python program to demonstrate
# indexing in numpy
import numpy as np

# An exemplar array
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

# Slicing array
temp = arr[:2, ::2]
print("Array with first 2 rows and alternate"
      "columns(0 and 2):\n", temp)

# Integer array indexing example
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print("\nElements at indices (0, 3), (1, 2), (2, 1),"
      "(3, 0):\n", temp)

# boolean array indexing example
cond = arr > 0  # cond is a boolean array
temp = arr[cond]
print("\nElements greater than 0:\n", temp)

In [ ]:
# Python program to demonstrate
# basic operations on single array
import numpy as np

a = np.array([1, 2, 5, 3])

# add 1 to every element
print("Adding 1 to every element:", a+1)

# subtract 3 from each element
print("Subtracting 3 from each element:", a-3)

# multiply each element by 10
print("Multiplying each element by 10:", a*10)

# square each element
print("Squaring each element:", a**2)

# modify existing array
a *= 2
print("Doubled each element of original array:", a)

# transpose of array
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])

print("\nOriginal array:\n", a)
print("Transpose of array:\n", a.T)

In [ ]:
# Python program to demonstrate
# unary operators in numpy
import numpy as np

arr = np.array([[1, 5, 6],
                [4, 7, 2],
                [3, 1, 9]])

# maximum element of array
print("Largest element is:", arr.max())
print("Row-wise maximum elements:",
      arr.max(axis=1))

# minimum element of array
print("Column-wise minimum elements:",
      arr.min(axis=0))

# sum of array elements
print("Sum of all array elements:",
      arr.sum())

# cumulative sum along each row
print("Cumulative sum along each row:\n",
      arr.cumsum(axis=1))
# cumulative sum along each col
print("Cumulative sum along each col:\n",
      arr.cumsum(axis=0))

In [ ]:
# Python program to demonstrate
# binary operators in Numpy
import numpy as np

a = np.array([[1, 2],
              [3, 4]])
b = np.array([[4, 3],
              [2, 1]])

# add arrays
print("Array sum:\n", a + b)

# multiply arrays (elementwise multiplication)
print("Array multiplication:\n", a*b)

# matrix multiplication
print("Matrix multiplication:\n", a.dot(b))

In [ ]:
# Python program to demonstrate
# universal functions in numpy
import numpy as np

# create an array of sine values
a = np.array([0, np.pi/2, np.pi])
print("Sine values of array elements:", np.sin(a))

# exponential values
a = np.array([0, 1, 2, 3])
print("Exponent of array elements:", np.exp(a))

# square root of array values
print("Square root of array elements:", np.sqrt(a))

In [ ]:
# Python Program to create a data type object
# containing a 32 bit big-endian integer
import numpy as np

# i4 represents integer of size 4 byte
# > represents big-endian byte ordering and
# < represents little-endian encoding.
# dt is a dtype object
dt = np.dtype('>i4')

print("Byte order is:", dt.byteorder)

print("Size is:", dt.itemsize)

print("Data type is:", dt.name)

In [ ]:
# Python program to demonstrate 
# the use of data type object with structured array.
import numpy as np
 
dt = np.dtype([('name', np.unicode_, 16), ('grades', np.float64, (2,))])
 
# x is a structured array with names and marks of students.
# Data type of name of the student is np.unicode_ and 
# data type of marks is np.float(64)
x = np.array([('Sarah', (8.0, 7.0)), ('John', (6.0, 7.0))], dtype=dt)
 
print(x[1])
print("Grades of John are: ",x[1]['grades'])
print("Names are: ",x['name'])

In [ ]:
import numpy as np 
 
a = np.array([1]) 
 
print("type is: ",type(a)) 
print("dtype is: ",a.dtype) 

In [ ]:
# initializing array with array values
# initializes array with signed integers
arr = array.array('i', [1, 2, 3]) 

# printing original array
print ("The new created array is : ",end="")
for i in range (0,3):
    print (arr[i], end=" ")

print ("\r")

In [ ]:
import time

print("Loading", end="")
for i in range(1):
    time.sleep(1)
    print("\rLoading" + "." * i, end="")

In [ ]:
# Python Program illustrating
# numpy.reshape() method

import numpy as geek

array = geek.arange(8)
print("Original array : \n", array)

# shape array with 2 rows and 4 columns
array = geek.arange(8).reshape(2, 4)
print("\narray reshaped with 2 rows and 4 columns : \n", array)

# shape array with 2 rows and 4 columns
array = geek.arange(8).reshape(4 ,2)
print("\narray reshaped with 2 rows and 4 columns : \n", array)

# Constructs 3D array
array = geek.arange(8).reshape(2, 2, 2)
print("\nOriginal array reshaped to 3D : \n", array)

print("A\n", geek.arange(4).reshape(2, 2), "\n")

print("A\n", geek.arange(40).reshape(2,2,2,5), "\n")

print("A\n", geek.arange(4, 20, 3), "\n")

In [ ]:
# Python Program illustrating
# numpy.flatten() method

import numpy as geek

array = geek.array([[1, 2], [3, 4]])

# using flatten method
array.flatten()
print(array)

#using fatten method 
array.flatten('F')
print(array)

In [ ]:
# np.ones	Creates an array filled with ones.
# np.zeros	Creates an array filled with zeros.
# np.full	Creates an array filled with a specified value.
# np.empty	Creates an uninitialized array (random contents).

In [ ]:
# syntax: np.ones(shape, dtype=None, order='C', *, like=None)
# numpy.zeros(shape, dtype = None, order = 'C')

# Create a 2x3 array of ones in column-major order (Fortran-style)
a=np.array([[1,2],[2,3]])
arr = np.ones((2, 2), order='F',like=a)
print(arr)


In [ ]:
import numpy as geek
 
print("A\n", geek.arange(4).reshape(2, 2), "\n")
print("A\n", geek.arange(4, 10), "\n")
print("A\n", geek.arange(4, 20, 3), "\n")
print(np.arange(1, 2, 0.1))


In [ ]:
# Synatx: numpy.linspace(start, stop, num=50, endpoint=True , retstep=False, dtype=None, axis=0)


import numpy as np
start = np.array([[1, 2], [4, 5]])
stop = np.array([[10, 20], [40, 50]])
result = np.linspace(start, stop, num=5, axis=1,retstep=True)
print(result)


In [ ]:
# numpy.eye(R, C = None, k = 0, dtype = type <‘float’>) : –The eye tool returns a 2-D array with  1’s as the diagonal and  0’s elsewhere. The diagonal can be main, upper, or lower depending on the optional parameter k. A positive k is for the upper diagonal, a negative k is for the lower, and a  0 k (default) is for the main diagonal.

# Python Programming illustrating
# numpy.eye method

import numpy as geek

# 2x2 matrix with 1's on main diagonal
b = geek.eye(2, dtype = float)
print("Matrix b : \n", b)

# matrix with R=4 C=5 and 1 on diagonal
# below main diagonal
a = geek.eye(4, 5, k = -3)
print("\nMatrix a : \n", a)

In [ ]:
x = np.linspace(-4, 4, 9) 
  
# numpy.linspace creates an array of 
# 9 linearly placed elements between 
# -4 and 4, both inclusive  
y = np.linspace(-5, 5, 11) 
  
# The meshgrid function returns 
# two 2-dimensional arrays  
x_1, y_1 = np.meshgrid(x, y) 
  
print("x_1 = ") 
print(x_1) 
print("y_1 = ") 
print(y_1)

In [ ]:
str = "geeksforgeeks"
 
# creating 1-d array
x = np.fromiter(str, dtype='U2')
print(x)

a=np.random.rand(2,3)
 
print(a)

In [ ]:
# numpy.max() This function return the maximum value in an array or along a specified axis.

a=np.array([[1,2],[20,3]])
# a=np.arange(0,1000)
 
# b=a.max(axis=1)
# b=a.min(axis=1)
b=a.argmax(axis=1)
# b=a.argmin(axis=1)
 
print(b)

In [ ]:
empty_array_2d = np.empty((3, 4))
print(empty_array_2d)
 
full_array_2d = np.full((3, 4), 5)
print(full_array_2d)

In [ ]:
# numpy.exp()– this mathematical function helps the user to calculate the exponential of all the elements in the input array.

# numpy.exp(array, out = None, where = True, casting = ‘same_kind’, order = ‘K’, dtype = None)

# Store the result in an existing array
output = np.zeros(3)
np.exp([1, 2, 3], out=output)
print(output)


In [ ]:

# creating a 1-D list (Horizontal) 
list1 = [1, 2, 3] 
  
# creating a 1-D list (Vertical) 
list2 = [[10], 
        [20], 
        [30]] 
  
# creating a vector1 
# vector as row 
vector1 = np.array(list1) 
  
# creating a vector 2 
# vector as column 
vector2 = np.array(list2) 
  
  
# showing horizontal vector 
print("Horizontal Vector") 
print(vector1) 
  
print("----------------") 
  
# showing vertical vector 
print("Vertical Vector") 
print(vector2) 

In [ ]:
gfg = np.core.records.fromrecords([(101, 'Jitender', 21), 
                                    (102, 'Deepak', 20)],  
                            names = 'Rollno, Name, Age') 
  
print(gfg)
print(gfg.Name)

In [ ]:
# The main difference between copy and view is that the copy is the new array whereas the view is the view of the original array. In other words, it can be said that the copy is physically stored at another location and the view has the same memory location as the original array.

arr = np.array([2, 4, 6, 8, 10])  
# creating view  
v = arr.view()  
# both arr and v have different id  
print("id of arr", id(arr))  
print("id of v", id(v))  
# changing original array  
# will effect view  
arr[0] = 12
# printing array and view  
print("original array- ", arr)  
print("view- \n", v)




In [ ]:
# creating copy of array 
arr = np.array([2, 4, 6, 8, 10])  

c = arr.copy() 
  
# both arr and c have different id 
print("id of arr", id(arr)) 
print("id of c", id(c)) 
  
# changing original array 
# this will not effect copy 
arr[0] = 12
  
# printing array and copy 
print("original array- ", arr) 
print("copy- ", c) 

In [ ]:
# Assigning Array to Variable
# Normal assignments do not make a copy of an array object. Instead, it uses the same ID of the original array to access it. 

# Any changes in either get reflected in the other.

arr = np.array([2, 4, 6, 8, 10]) 
  
# assigning arr to nc 
nc = arr 
  
# both arr and nc have same id 
print("id of arr", id(arr)) 
print("id of nc", id(nc)) 
  
# updating nc 
nc[0]= 12
  
# printing the values 
print("original array- ", arr) 
print("assigned array- ", nc) 

In [ ]:
arr = np.array([2, 4, 6, 8, 10]) 
  
# creating copy of array 
c = arr.copy() 
  
# creating view of array 
v = arr.view() 

a=arr
a[0]=0  
# printing base attribute of copy and view 
print(c.base) 
print(v.base) 
print(a.base) 
print(a)
print(arr)
# From the above code we can see that object ‘c’ returned None meaning it is a copy and owns the data.

# Object ‘v’ returns the original array meaning it is a view and does not own the data.

In [ ]:
# creating an array
arr = np.array([1, 8, 3, 3, 5])
print('Original Array : ', arr)
 
# appending to the array
arr = np.append(arr, [7])
print('Array after appending : ', arr)


arr1 = np.array([1, 2, 3])
print('First array is : ', arr1)
 
# creating another array
arr2 = np.array([4, 5, 6])
print('Second array is : ', arr2)
 
# appending arr2 to arr1
arr = np.append(arr1, arr2)
print('Array after appending : ', arr)

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])
 
combined = np.concatenate((arr1, arr2), axis=0)
print(combined)

In [ ]:
# Appending with a Different Array Type
# In this example, a 1D integer array arr and a 1D float array arr_float are appended together using np.append(), resulting in an upcasted float array as the output.

 
arr = np.array([1, 2, 3])
arr_float = np.array([4.0, 5.0])
 
combined = np.append(arr, arr_float)
print(combined)  # Output: [1. 2. 3. 4. 5.]

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
values_to_append = [np.array([6, 7]), np.array([8, 9])]
combined = np.concatenate([arr] + values_to_append)
print(combined)

In [ ]:
arr = np.arange(1, 13).reshape(2, 6)
print('Original Array')
print(arr, '\n')
 
# create another array which is
# to be appended column-wise
col = np.arange(5, 11).reshape(1, 6)
print('Array to be appended column wise')
print(col)
arr_col = np.append(arr, col, axis=0)
print('Array after appending the values column wise')
print(arr_col, '\n')
 
# create an array which is
# to be appended row wise
row = np.array([1, 2]).reshape(2, 1)
print('Array to be appended row wise')
print(row)
arr_row = np.append(arr, row, axis=1)
print('Array after appending the values row wise')
print(arr_row)

In [ ]:
my_array = np.arange(12).reshape(4, 3)
print("Original array:")
print(my_array)
 
# swapping the column with index of 
# original array
my_array[:, [2, 0]] = my_array[:, [0, 2]]
print("After swapping arrays the last column and first column:")
print(my_array)

In [ ]:
# Add a New Axis to a Numpy Array
#     Using numpy.newaxis()
#     Using numpy.expand_dims()
#     Simultaneously insert many axes in the array
#     Using numpy.reshape() a Single Axis

In [ ]:
arr = np.arange(5*5).reshape(5, 5)
print(arr.shape)
 
# promoting 2D array to a 5D array
# arr[None, ..., None, None]
arr_5D = arr[np.newaxis, ..., np.newaxis, np.newaxis]
 
print(arr_5D.shape)

In [ ]:
x = np.zeros((3, 4))
y = np.expand_dims(x, axis=2).shape
print(y)

In [ ]:
arr = np.arange(5*5).reshape(5,5)
print(arr.shape)
 
newaxes = (2, 3, 4)
arr_5D = np.expand_dims(arr, axis=newaxes)
print(arr_5D.shape)

In [ ]:
arr = np.arange(6)
arr_reshape = arr.reshape((2, 3))

In [ ]:
# same same with vstack
in_arr1 = geek.array([ 1, 2, 3] ) 
print ("1st Input array : \n", in_arr1)  
  
in_arr2 = geek.array([ 4, 5, 6] ) 
print ("2nd Input array : \n", in_arr2)  
  
# Stacking the two arrays horizontally 
out_arr = geek.hstack((in_arr1, in_arr2)) 
print ("Output horizontally stacked array:\n ", out_arr) 

in_arr1 = geek.array([[ 1, 2, 3], [ -1, -2, -3]] ) 
print ("1st Input array : \n", in_arr1)  
  
in_arr2 = geek.array([[ 4, 5, 6], [ -4, -5, -6]] ) 
print ("2nd Input array : \n", in_arr2)  
  
# Stacking the two arrays horizontally 
out_arr = geek.hstack((in_arr1, in_arr2)) 
print ("Output stacked array :\n ", out_arr) 

In [ ]:
# NumPy provides various functions to combine arrays. In this article, we will discuss some of the major ones.

# numpy.concatenate
# numpy.stack
# numpy.block

In [ ]:
# numpy.concatenate((array1, array2, ...), axis=0)
array_1 = np.array([1, 2]) 
array_2 = np.array([3, 4]) 
  
array_new = np.concatenate((array_1, array_2)) 
print(array_new) 


# array_1 = np.array([[1, 2], [3, 4]]) 
# array_2 = np.array([[5, 6], [7, 8]]) 
  
# array_new = np.concatenate((array_1, array_2), axis=0) 
# print(array_new) 

In [ ]:
# numpy.stack(arrays, axis=0)
array_1 = np.array([1, 2, 3, 4]) 
array_2 = np.array([5, 6, 7, 8]) 
  
array_new = np.stack((array_1, array_2), axis=0) 
# array_new = np.concatenate((array_1, array_2), axis=0) 

print(array_new) 

In [ ]:
# numpy.block(arrays)
block_1 = np.array([[1, 1], [1, 1]]) 
block_2 = np.array([[2, 2, 2], [2, 2, 2]]) 
block_3 = np.array([[3, 3], [3, 3], [3, 3]]) 
block_4 = np.array([[4, 4, 4], [4, 4, 4], [4, 4, 4]]) 
  
block_new = np.block([ 
    [block_1, block_2], 
    [block_3, block_4] 
]) 
  
print(block_new)

In [ ]:
# Combining a one and a two-dimensional NumPy Array

# Syntax: numpy.nditer(op, flags=None, op_flags=None, op_dtypes=None, order=’K’, casting=’safe’, op_axes=None, itershape=None, buffersize=0)

num_1d = np.arange(5) 
print("One dimensional array:") 
print(num_1d) 
  
num_2d = np.arange(10).reshape(2,5) 
print("\nTwo dimensional array:") 
print(num_2d) 
  
# Combine 1-D and 2-D arrays and display  
# their elements using numpy.nditer()  
for a, b in np.nditer([num_1d, num_2d]): 
    print("%d:%d" % (a, b),)

In [ ]:
# Python | Numpy np.ma.concatenate() method

# Syntax : np.ma.concatenate([list1, list2])

gfg1 = np.array([1, 2, 3]) 
gfg2 = np.array([4, 5, 6]) 
  
# using np.ma.concatenate() method 
print(np.ma.concatenate([gfg1, gfg2]))
print(np.ma.concatenate([[gfg1],[gfg2]]))

In [ ]:
# Syntax : numpy.dstack((array1, array2))
# Return : Return combined array index by index.

gfg1 = np.array([1, 2, 3]) 
gfg2 = np.array([4, 5, 6]) 
  
# using numpy.dstack() method 
print(np.dstack((gfg1, gfg2)))

gfg1 = np.array([[10], [2], [13]]) 
gfg2 = np.array([[41], [55], [6]]) 
  
# using numpy.dstack() method 
print(np.dstack((gfg1, gfg2)))  

In [159]:
# The split(), hsplit(), vsplit(), and dsplit() functions are important tools for dividing arrays along various axes and dimensions
Arr = np.array([1, 2, 3, 4, 5, 6])
print(np.array_split(arr, 4)) # for unequal splits
print(np.split(arr, 3)) # for equal splits

array = np.array([[3, 2, 1], [8, 9, 7], [4, 6, 5]])
# Splitting the array into 3 equal parts along the second axis (axis=1)
result = print(np.split(array, 3, axis=1))


matrix = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9],[10, 11, 12]])
# Vertical splitting into 2 subarrays along axis=0
result = print(np.vsplit(matrix, 2)) # only equal split otherwise error


matrix = np.array([[1, 2],[4, 5],[7, 8],[10, 11]])
# Horizontal splitting into 2 subarrays along axis=1
result = print(np.hsplit(matrix, 2)) # only equal split otherwise error

original_3d_array = np.arange(24).reshape((2, 3, 4))
# Splitting along axis=2 (third axis)
result = print(np.dsplit(original_3d_array, 2))

[array([0, 1]), array([2, 3]), array([4]), array([5])]
[array([0, 1]), array([2, 3]), array([4, 5])]
[array([[3],
       [8],
       [4]]), array([[2],
       [9],
       [6]]), array([[1],
       [7],
       [5]])]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]
[array([[ 1],
       [ 4],
       [ 7],
       [10]]), array([[ 2],
       [ 5],
       [ 8],
       [11]])]
[array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[12, 13],
        [16, 17],
        [20, 21]]]), array([[[ 2,  3],
        [ 6,  7],
        [10, 11]],

       [[14, 15],
        [18, 19],
        [22, 23]]])]


In [ ]:
# How to compare two NumPy arrays?

an_array = np.array([[1, 2], [3, 4]])
another_array = np.array([[1, 2], [3, 4]])

# Element-wise comparison
comparison = an_array == another_array
print(comparison)

# Check if all elements are equal
equal_arrays = (comparison.all())
print(equal_arrays)

# Syntax : numpy.greater(x1, x2[, out])
# Syntax : numpy.greater_equal(x1, x2[, out])
# Syntax : numpy.less(x1, x2[, out])
# Syntax : numpy.less_equal(x1, x2[, out])


a = np.array([101, 99, 87])
b = np.array([897, 97, 111])
 
print("Array a: ", a)
print("Array b: ", b)
 
print("a > b")
print(np.greater(a, b))
 
print("a >= b")
print(np.greater_equal(a, b))
 
print("a < b")
print(np.less(a, b))
 
print("a <= b")
print(np.less_equal(a, b))


arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
 
 
# Comparing the arrays
if np.array_equal(arr1, arr2):
    print("Equal")
else:
    print("Not Equal")

In [ ]:
arr1 = np.array([10, 20, 30, 40]) 
print("array1 ", arr1) 
arr2 = np.array([20, 40, 60, 80]) 
print("array2 ", arr2) 
print("Union of two arrays :", np.union1d(arr1, arr2))

#  if array passed as arguments to function numpy.union1d is 2-dimensional, then they are flattened to 1-dimension.

In [ ]:
# If we want to find union of more than two arrays, then we can find that by using functools.reduce function.

from functools import reduce
array = print(reduce(np.union1d, ([1, 2, 3], [1, 3, 5], [2, 4, 6], [0, 0, 0])) )

In [ ]:
# numpy.unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None)
arr2D = np.array([[11, 11, 12, 11],
                     [13, 11, 12, 11],
                     [16, 11, 12, 11],
                     [11, 11, 12, 11]])
 
# print('Original Array :' ,arr2D)
uniqueRows = np.unique(arr2D,return_index=True,return_inverse=True,return_counts=True)
print('Unique Rows:', uniqueRows, sep = '\n')

In [ ]:
gfg = geek.array((0, 0, 0, 0, 1, 5, 7, 0, 6, 2, 9, 0, 10, 0, 0)) 
  
# without trim parameter 
# returns an array without leading and trailing zeros  
  
res = geek.trim_zeros(gfg,trim='fb') 
print(res)

# Matrix manipulation in Python


<!-- Operation on Matrix : 

1. add() :- This function is used to perform element wise matrix addition. 
2. subtract() :- This function is used to perform element wise matrix subtraction. 
3. divide() :- This function is used to perform element wise matrix division. 
4. multiply() :- This function is used to perform element wise matrix multiplication. 
5. dot() :- This function is used to compute the matrix multiplication, rather than element wise multiplication.  -->

In [165]:
# Python code to demonstrate matrix operations 
# add(), subtract() and divide() 

# importing numpy for matrix operations 
import numpy 

# initializing matrices 
x = numpy.array([[1, 2], [4, 5]]) 
y = numpy.array([[7, 8], [9, 10]]) 

# using add() to add matrices 
print ("The element wise addition of matrix is : ") 
print (numpy.add(x,y)) 

# using subtract() to subtract matrices 
print ("The element wise subtraction of matrix is : ") 
print (numpy.subtract(x,y)) 

# using divide() to divide matrices 
print ("The element wise division of matrix is : ") 
print (numpy.divide(x,y))
print ("The element wise multiplication of matrix is : ") 
print (numpy.multiply(x,y)) 

# using dot() to multiply matrices 
print ("The product of matrices is : ") 
print (numpy.dot(x,y))

# using sqrt() to print the square root of matrix 
print ("The element wise square root is : ") 
print (numpy.sqrt(x)) 

# using sum() to print summation of all elements of matrix 
print ("The summation of all matrix element is : ") 
print (numpy.sum(y,axis=None))
# using "T" to transpose the matrix 
print ("The transpose of given matrix is : ") 
print (x.T)

The element wise addition of matrix is : 
[[ 8 10]
 [13 15]]
The element wise subtraction of matrix is : 
[[-6 -6]
 [-5 -5]]
The element wise division of matrix is : 
[[0.14285714 0.25      ]
 [0.44444444 0.5       ]]
The element wise multiplication of matrix is : 
[[ 7 16]
 [36 50]]
The product of matrices is : 
[[25 28]
 [73 82]]
The element wise square root is : 
[[1.         1.41421356]
 [2.         2.23606798]]
The summation of all matrix element is : 
34
The transpose of given matrix is : 
[[1 4]
 [2 5]]


In [171]:
import numpy.matlib 
# Syntax  :  numpy.matlib.identity(n, dtype=None)
# desired 3 x 3 output square identity matrix  
out_mat = np.matlib.identity(3)  
print ("Output matrix : ", out_mat,sep='\n') 

Output matrix : 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [173]:
# creating first matrix
A = np.array([[1, 2], [3, 4]])
 
# creating second matrix
B = np.array([[4, 5], [6, 7]])
# adding two matrix
print("Addition of two matrix")
print(np.add(A, B))
print(np.subtract(A, B))

Addition of two matrix
[[ 5  7]
 [ 9 11]]
[[-3 -3]
 [-3 -3]]


In [178]:
# creating two matrices 
p = [[1, 2], [2, 3]] 
q = [[4, 5], [6, 7]]

print(np.dot(p,q))

arr1 = np.eye(3) 
arr = np.ones((3, 3)) * 3
gfg = arr1.dot( arr ).dot(arr)
  
print( gfg) 

[[16 19]
 [26 31]]
[[27. 27. 27.]
 [27. 27. 27.]
 [27. 27. 27.]]


In [180]:
# input two matrices
mat1 = ([1, 6, 5],[3 ,4, 8],[2, 12, 3])
mat2 = ([3, 4, 6],[5, 6, 7],[6,56, 7])

# This will return matrix product of two array
# res = mat1 @ mat2

# # print resulted matrix
# print(res)

In [216]:
# Syntax : np.linalg.eigvals(matrix)

# Return : Return the eigen values of a matrix.

# using np.linalg.eigvals() method 
print(np.linalg.eigvals([[1, 2], [3, 4]]))
# calculating the determinant of matrix 
print(np.linalg.det([[1, 2], [3, 4]]))
print(np.linalg.inv([[1, 2], [3, 4]]))

[-0.37228132  5.37228132]
-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


In [213]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]') 
               
# applying matrix.transpose() method 
geek = gfg.transpose() 
     
print(geek)

[[ 4 12  4]
 [ 1  3  5]
 [ 9  1  6]]


In [239]:
# make matrix with numpy 
gfg = np.matrix('[4, 1; 12, 3]') 
              
# applying matrix.var() method 
geek = gfg.var(axis=None)
    
print(geek)

17.5


# Operations on NumPy Array


In [ ]:
# Python program explaining
# bitwise_and() function

import numpy as geek
in_num1 = 10
in_num2 = 11
print(geek.bitwise_and(in_num1, in_num2)) 

in_arr1 = [2, 8, 125]
in_arr2 = [3, 3, 115]
print(geek.bitwise_and(in_arr1, in_arr2))  # geek.bitwise_or, geek.bitwise_xor

print(geek.invert(10)) # inversion
print(geek.left_shift(5,2))

# Python program explaining
# left_shift() function

in_arr = [2, 8, 15]
bit_shift =[3, 4, 5]
print(geek.left_shift(in_arr, bit_shift) ) # right_shift


10
[  2   0 113]
-11
20
[ 16 128 480]


In [228]:
# numpy.binary_repr(number, width=None) : 
# This function is used to represent binary form of the input number as a string.For negative numbers, if width is not given, a minus sign is added to the front. If width is given, the two’s complement of the number is returned, with respect to that width.

print(np.binary_repr(-10,width=True))

10110


C:\Users\gragh\AppData\Local\Temp\ipykernel_3044\1249531389.py:4: DeprecationWarning: Insufficient bit width provided. This behavior will raise an error in the future.
  print(np.binary_repr(-10,width=True))


In [233]:
# Python program explaining
# packbits() function
import numpy as np

# This function is used to packs the elements of a binary-valued array into bits in a uint8 array.The result is padded to full bytes by inserting zero bits at the end.

# creating an array using 
# array function
a = np.array([[[1,0,1], #10100000
             [0,1,0]], #01000000
             [[1,1,0], # 11000000
             [0,0,1]]]) #00100000

# packing elements of an array
# using packbits() function
b = np.packbits(a, axis=-1)

print(b)

b=np.unpackbits(b) # [1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
print(b)


a = np.array([[2], [7], [23]], dtype=np.uint8)

# packing elements of an array
# using packbits() function
b = np.unpackbits(a, axis = 1)
print(b)

[[[160]
  [ 64]]

 [[192]
  [ 32]]]
[1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
[[0 0 0 0 0 0 1 0]
 [0 0 0 0 0 1 1 1]
 [0 0 0 1 0 1 1 1]]


In [ ]:
# Sin_Values = np.sin(in_array)
# cos_Values = np.cos(in_array)
# tan()	Compute tangent element-wise.
# arcsin()	Inverse sine, element-wise.
# arccos()	Trigonometric inverse cosine, element-wise.
# arctan()	Trigonometric inverse tangent, element-wise.
# arctan2()	Element-wise arc tangent of x1/x2 choosing the quadrant correctly.
# degrees()	Convert angles from radians to degrees.
# rad2deg()	Convert angles from radians to degrees.
# deg2rad	Convert angles from degrees to radians.
# radians()	Convert angles from degrees to radians.
# hypot()	Given the “legs” of a right triangle, return its hypotenuse.
# unwrap()	Unwrap by changing deltas between values to 2*pi complement.
# Sinh_Values = np.sinh(in_array)
# cosh_Values = np.cosh(in_array)
# tanh()	Compute hyperbolic tangent element-wise.
# arcsinh()	Inverse hyperbolic sine element-wise.
# arccosh()	Inverse hyperbolic cosine, element-wise.
# arctanh()	Inverse hyperbolic tangent element-wise.


In [234]:
# Functions for Rounding –
# numpy.around(arr, decimals = 0, out = None) : This mathematical function helps user to evenly round array elements to the given number of decimals.

# Python program explaining
# around() function
 
import numpy as np
 
in_array = [.5, 1.5, 2.5, 3.5, 4.5, 10.1]
print ("Input array : \n", in_array)
 
round_off_values = np.around(in_array)
print ("\nRounded values : \n", round_off_values)
 
 
in_array = [.53, 1.54, .71]
print ("\nInput array : \n", in_array)
 
round_off_values = np.around(in_array)
print ("\nRounded values : \n", round_off_values)
 
in_array = [.5538, 1.33354, .71445]
print ("\nInput array : \n", in_array)
 
round_off_values = np.around(in_array, decimals = 3)
print ("\nRounded values : \n", round_off_values)

Input array : 
 [0.5, 1.5, 2.5, 3.5, 4.5, 10.1]

Rounded values : 
 [ 0.  2.  2.  4.  4. 10.]

Input array : 
 [0.53, 1.54, 0.71]

Rounded values : 
 [1. 2. 1.]

Input array : 
 [0.5538, 1.33354, 0.71445]

Rounded values : 
 [0.554 1.334 0.714]


In [ ]:
# # numpy.round_(arr, decimals = 0, out = None) : This mathematical function round an array to the given number of decimals.
# # rint()	Round to nearest integer towards zero.
# # fix()	Round to nearest integer towards zero.
# # floor()	Return the floor of the input, element-wise.
# # ceil()	Return the ceiling of the input, element-wise.
# # trunc()	Return the truncated value of the input, element-wise.

# numpy.log(x[, out] = ufunc ‘log1p’) 
# expm1()	Calculate exp(x) – 1 for all elements in the array.
# exp2()	Calculate 2**p for all p in the input array.
# log10()	Return the base 10 logarithm of the input array, element-wise.
# log2()	Base-2 logarithm of x.
# log1p()	Return the natural logarithm of one plus the input array, element-wise.
# logaddexp()	Logarithm of the sum of exponentiations of the inputs.
# logaddexp2()	Logarithm of the sum of exponentiations of the inputs in base-2.
# out_num = np.reciprocal(in_num)
# out = np.divide(arr1, arr2)

# add()	Add arguments element-wise.
# positive()	Numerical positive, element-wise.
# negative()	Numerical negative, element-wise.
# multiply()	Multiply arguments element-wise.
# power()	First array elements raised to powers from second array, element-wise.
# subtract()	Subtract arguments, element-wise.
# true_divide()	Returns a true division of the inputs, element-wise.
# floor_divide()	Return the largest integer smaller or equal to the division of the inputs.
# float_power()	First array elements raised to powers from second array, element-wise.
# mod()	Return the element-wise remainder of division.
# remainder()	Return element-wise remainder of division.
# divmod()	Return element-wise quotient and remainder simultaneously.

# numpy.conj(x[, out] = ufunc ‘conjugate’) : This function helps the user to conjugate any complex number.
# numpy.cbrt(arr, out = None, ufunc ‘cbrt’) : This mathematical function helps user to calculate cube root of x for all x being the array elements.

# numpy.clip() : This function is used to Clip (limit) the values in an array.

# convolve()	Returns the discrete, linear convolution of two one-dimensional sequences.
# sqrt()	Return the non-negative square-root of an array, element-wise.
# square()	Return the element-wise square of the input.
# absolute()	Calculate the absolute value element-wise.
# fabs()	Compute the absolute values element-wise.
# sign()	Returns an element-wise indication of the sign of a number.
# interp()	One-dimensional linear interpolation.
# maximum()	Element-wise maximum of array elements.
# minimum()	Element-wise minimum of array elements.
# real_if_close()	If complex input returns a real array if complex parts are close to zero.
# nan_to_num()	Replace NaN with zero and infinity with large finite numbers.
# heaviside()	Compute the Heaviside step function.

In [235]:
# converting to lowercase
print(np.char.lower(['GEEKS', 'FOR']))
 
# converting to lowercase
print(np.char.lower('GEEKS'))

['geeks' 'for']
geeks


In [242]:
# Python program explaining
# numpy.split() function
 
import numpy as np
 
# splitting a string
print(np.char.split('geeks for geeks'))
 
# splitting a string
print(np.char.split('geeks, for, geeks', sep = ','))

# splitting a string
print(np.char.split('geeks for geeks'))
 
# splitting a string
print(np.char.split('geeks, for, geeks', sep = ','))

# splitting a string
print(np.char.join('-', 'geeks'))
 
# splitting a string
print(np.char.join(['-', ':'], ['geeks', 'for']))

['geeks', 'for', 'geeks']
['geeks', ' for', ' geeks']
['geeks', 'for', 'geeks']
['geeks', ' for', ' geeks']
g-e-e-k-s
['g-e-e-k-s' 'f:o:r']


In [ ]:
# numpy.strip()	It is used to remove all the leading and trailing spaces from a string.
# numpy.capitalize()	It converts the first character of a string to capital (uppercase) letter. If the string has its first character as capital, then it returns the original string.
# numpy.center()	It creates and returns a new string which is padded with the specified character..
# numpy.decode()	It is used to convert from one encoding scheme, in which argument string is encoded to the desired encoding scheme.
# numpy.encode()	Returns the string in the encoded form
# numpy.ljust()	Return an array with the elements of a left-justified in a string of length width.
# numpy.rjust()	For each element in a, return a copy with the leading characters removed.
# numpy.strip()	For each element in a, return a copy with the leading and trailing characters removed.
# numpy.lstrip()	Convert angles from degrees to radians.
# numpy.rstrip()	For each element in a, return a copy with the trailing characters removed.
# numpy.partition()	Partition each element in a around sep.
# numpy.rpartition	Partition (split) each element around the right-most separator.
# numpy.rsplit()	For each element in a, return a list of the words in the string, using sep as the delimiter string.
# numpy.title()	It is used to convert the first character in each word to Uppercase and remaining characters to Lowercase in string and returns new string.
# numpy.upper()	Returns the uppercased string from the given string. It converts all lowercase characters to uppercase.If no lowercase characters exist, it returns the original string.

In [243]:
# Python program explaining
# numpy.count() function
 
import numpy as np
 
a=np.array(['geeks', 'for', 'geeks'])
 
# counting a substring
print(np.char.count(a,'geek'))
 
# counting a substring
print(np.char.count(a, 'fo'))

[1 0 1]
[0 1 0]


In [245]:
# numpy.rfind() : This function returns the highest index of the substring if found in given string. If not found then it returns -1.

# Python program explaining
# numpy.rfind() function
 
import numpy as np
 
a=np.array(['geeks', 'for', 'geeks'])
 
# counting a substring
print(np.char.rfind(a,'geek'))
 
# counting a substring
print(np.char.rfind(a, 'fo'))


print(np.char.isnumeric('geeks'))
 
# counting a substring
print(np.char.isnumeric('12764'))

[ 0 -1  0]
[-1  0 -1]
False
True


<!-- numpy.find()	It returns the lowest index of the substring if it is found in given string. If its is not found then it returns -1.
numpy.index()	It returns the position of the first occurrence of substring in a string
numpy.isalpha()	It returns “True” if all characters in the string are alphabets, Otherwise, It returns “False”.
numpy.isdecimal()	It returns true if all characters in a string are decimal. If all characters are not decimal then it returns false.
numpy.isdigit()	It returns “True” if all characters in the string are digits, Otherwise, It returns “False”.
numpy.islower()	It returns “True” if all characters in the string are lowercase, Otherwise, It returns “False”.
numpy.isspace()	Returns true for each element if there are only whitespace characters in the string and there is at least one character, false otherwise.
numpy.istitle()	Returns true for each element if the element is a titlecased string and there is at least one character, false otherwise.
numpy.isupper()	Returns true for each element if all cased characters in the string are uppercase and there is at least one character, false otherwise.
numpy.rindex()	Returns the highest index of the substring inside the string if substring is found. Otherwise it raises an exception.
numpy.startswith()	Returns True if a string starts with the given prefix otherwise returns False. -->

In [250]:
# comparing a string elementwise
# using equal() method
a=np.char.equal('geeks','for')
print(a)
a = np.char.not_equal('geeks', 'for')
print(a)
a=np.char.greater('geeks','for')
print(a)

# numpy.greater_equal()	It checks whether string1 >= string2 or not.
# numpy.less_equal()	It checks whether string1 is <= string2 or not.
# numpy.less()	It check whether string1 is lesser than string2 or not.

False
True
True
